name:                csvtojson
version:             0.1.0.0
github:              "mcklyde/soundcsvtojson"
license:             BSD3
author:              "mcklyde"
maintainer:          "mcklyde@lagnada.com"
copyright:           "2019 McKlyde Lagnada"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/mcklyde/soundcsvtojson.git

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- regex-compat
- bytestring
- directory

library:
  source-dirs: src

executables:
  csvtojson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvtojson

tests:
  csvtojson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvtojson
